### ISSUE TITLE
Invalid italics/dropped * in table.md and readme.md

### ISSUE THREAD

**Issue by spenserblack** [corollari/linusrants#1]
Some censoring is resulting in words being italicized that shouldn't be. A quick solution might be to find any `*` that isn't preceded or followed by a space or punctuation, and escape it like `\*`.

# Example
"ONE F*CKING BYTE AT A TIME ... Who the f*ck"

**Comment by corollari** [comment]
Good catch! Would you be interested in sending a PR fixing it?

**Comment by spenserblack** [comment]
No problem! PR Sent.
